linters-settings:
  dupl:
    threshold: 30
  funlen:
    lines: 100
    statements: 30
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: mynews
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  tagliatelle:
    case:
      rules:
        json: goCamel

linters:
  enable-all: true

run:
  timeout: 5m
