linters-settings:
  dupl:
    threshold: 30
  funlen:
    lines: 100
    statements: 30
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: github.com/golangci/golangci-lint
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  misspell:
    locale: US
  nakedret:
    max-func-lines: 0
  tagliatelle:
    case:
      rules:
        json: goCamel

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - gocognit
    - prealloc
    - wsl
    - goprintffuncname
    - rowserrcheck
    - gomnd
    - godox
    - goerr113
    - gomodguard
    - godot
    - testpackage
    - nestif
    - nolintlint
    - asciicheck
    - exhaustive
    - exportloopref
    - gofumpt
    - goheader
    - nlreturn
    - noctx
    - sqlclosecheck
    - cyclop
    - durationcheck
    - forcetypeassert
#    - gci
    - gomoddirectives
    - importas
    - nilerr
    - promlinter
    - revive
    - tagliatelle
    - testpackage
    - wastedassign
    - ifshort
    # - interfacer # Deprecated
    # - golint # Deprecated
    # - maligned # Deprecated
    # - scopelint # Deprecated

run:
  timeout: 5m
