name: mynews
version: '1.3.0'
summary: Personalized news feed parser & broadcast
description: Easily specify your RSS/Atom sources and broadcast preferences to get personalized news feed.
base: core18
parts:
  mynews:
    plugin: go
    source: .
apps:
  mynews:
    environment:
      MYNEWS_CONFIG_FILE: $SNAP_USER_COMMON/config.json
    command: bin/mynews
    plugs:
      - network
