name: mynews
version: '1.1.0'
summary: Personal news feed parser & broadcaster
description: |
    Easy specification of RSS/Atom sources and multiple broadcast options to personalize news feed.
confinement: strict
base: core18
type: app
grade: stable
icon: ./icon.svg
parts:
  scrape:
    plugin: nil
    build-snaps: [go]
    source: .
    source-type: git
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build -o ../../../prime/bin/scrape
apps:
  scrape:
    command: bin/scrape
    plugs:
      - network
