name: mynews
version: '1.4.0'
summary: Personalized news feed parser & broadcast
description: Easily specify your RSS/Atom sources and broadcast preferences to get personalized news feed.
base: core20
parts:
  mynews:
    plugin: go
    source: .
apps:
  mynews:
    environment:
      MYNEWS_CONFIG_FILE: $SNAP_COMMON/config.json
      MYNEWS_STORAGE_FILE: $SNAP_COMMON/data.json
    command: bin/mynews
    plugs:
      - network
  mynewsd:
    environment:
      MYNEWS_CONFIG_FILE: $SNAP_COMMON/config.json
      MYNEWS_STORAGE_FILE: $SNAP_COMMON/data.json
    command: bin/mynews
    daemon: simple
    plugs:
      - network
