name: mynews
version: '1.2.1'
summary: Personalized news feed parser & broadcast
description: |
    Easily specify your RSS/Atom sources and broadcast preferences to get personalized news feed.
confinement: strict
base: core18
type: app
grade: stable
icon: ./icon.svg
parts:
  mynews:
    plugin: nil
    build-snaps: [go]
    source: .
    source-type: git
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export GO111MODULE=on
      export CGO_ENABLED=0
      go build -o ../../../prime/bin/mynews
apps:
  mynews:
    command: bin/mynews
    plugs:
      - network
layout:
  /etc/config.json:
    symlink: $SNAP_DATA/etc/mynews/config.json
